# choose mode ('docs' or 'local')
mode = "local"

# problem id (it is used for the name of output html file)
id = "B"

params_path = "./tests/constraints.hpp"
# pato to a statement, output params
[[statements]]
path = "./statement/statement.md"
lang = "ja"

# write constraints
[constraints]
    MIN_N = 1
    MAX_N = 100000
    MIN_U = 1
    MAX_U = 100000
    MIN_V = 1
    MAX_V = 100000
