// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 1;
const long long int MAX_N = 100000;
const long long int MIN_U = 1;
const long long int MAX_U = 100000;
const long long int MIN_V = 1;
const long long int MAX_V = 100000;
const long long int MIN_H = 1;
const long long int MAX_H = 100;
