# choose mode ('docs' or 'local')
mode = "local"

# problem id (it is used for the name of output html file)
id = "A"

# pato to a statement, output params
statement_path = "./statement/statement.md"
params_path = "./tests/constraints.hpp"
lang = "ja"

# write constraints
[constraints]
    MIN_N = 1
    MAX_N = 200000
    MIN_A = 1
    MAX_A = 1000000000
