// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 1;
const long long int MAX_N = 100;
const long long int MIN_X = 1;
const long long int MAX_X = 100;
const long long int MIN_A = 1;
