// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_NM = 1;
const long long int MAX_NM = 100000;
const long long int MIN_XY = 0;
const long long int MAX_XY = 1000000000;
const long long int MIN_Z = 0;
const long long int MAX_Z = 1000000000;
