# choose mode ('docs' or 'local')
mode = "local"

# problem id (it is used for the name of output html file)
id = "B"
params_path = "./tests/constraints.hpp"

# pato to a statement, output params
[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]

# write constraints
[constraints]
    MIN_N = 1
    MAX_N = 50000
    MIN_U = 1
    MAX_U = 1000000000
    MIN_V = 1
    MAX_V = 1000000000
    MIN_H = 1
    MAX_H = 100
