# choose mode ('docs' or 'local')
mode = "local"

# problem id (it is used for the name of output html file)
id = "A"

# pato to a statement, output params
params_path = "./tests/constraints.hpp"
lang = "ja"

[[statements]]
path = "./statement/statement.md"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]

# write constraints
[constraints]
    MIN_NM = 1
    MAX_NM = 100000
    MIN_XC = 1
    MAX_XC = 100000
