# choose mode ('docs' or 'local')
mode = "local"

# problem id (it is used for the name of output html file)
id = "A"

# pato to a statement, output params
statement_path = "./statement/statement.md"
params_path = "./tests/constraints.hpp"
lang = "ja"

# write constraints
[constraints]
    MIN_NM = 1
    MAX_NM = 100000
    MIN_XC = 1
    MAX_XC = 100000
