# problem id (it is used for the name of output html file)
id = "F"

# pato to a statement, output params
params_path = "./tests/constraints.hpp"

[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]


# write constraints
[constraints]
    MIN_N = 1
    MAX_N = 4000
