// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 2;
const long long int MAX_N = 100000;
const long long int MIN_p = 300;
const long long int MAX_p = 9999999;
