// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 2;
const long long int MAX_N = 100000;
const long long int MIN_PC = 300;
const long long int MAX_PC = 9999999;
